# base image
FROM node:16-alpine

WORKDIR '/app'

# copy file to container that are needed for installation
COPY package.json .

#install dependencies
RUN npm install

# copy files that change often to container
COPY . .

# default commands
CMD ["npm", "run", "start"]

# hot refresh
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id>